# Este arquivo substitui a necessidade de configurar o sys.path manualmente, tornando os imports do projeto disponíveis automaticamente.

[pytest]        
# indica que este é o arquivo de configuração do pytest.

pythonpath = .  
# faz o pytest adicionar automaticamente a pasta raiz do projeto ao sys.path
# substituindo o sys.path.append(root_folder_path) no notebook

filterwarnings = ignore::DeprecationWarning
# Mantém a saída dos testes mais limpa, sem poluição de warnings desnecessários.

